repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.2.1"
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
          - "--remove-all-unused-imports"

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.7"
    hooks:
      - id: bandit

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

  - repo: https://github.com/jazzband/pip-tools
    rev: "7.3.0"
    hooks:
      - id: pip-compile
        args: ["--no-emit-index-url"]

  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.10"
    hooks:
      - id: vulture
        args: ["--min-confidence", "80", "congressionalrecord"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
        args: ["--rev-range", "74cd4a6..HEAD"]

  - repo: https://github.com/regebro/pyroma
    rev: "4.2"
    hooks:
      - id: pyroma
