
[project]
name = 'congressionalrecord'
version = '2.0.5'
description = 'Parse the U.S. Congressional Record from GovInfo.'
authors = [
    { name="Nick Judd", email="nick@nclarkjudd.com" },
]
readme = "README.md"
requires-python = ">=3.1"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD3",
    "Operating System :: OS Independent",
]
dependencies = [
    'beautifulsoup4',
    'soupsieve',
    'lxml',
    'numpy',
    'psycopg2-binary',
    'urllib3',
    'pyelasticsearch',
    'SQLAlchemy ',
    'requests[security]',
    'PyYAML',
    'unicodecsv',
    'future'
    ]

[project.urls]
Homepage='https://github.com/unitedstates/congressional-record'
Issues='https://github.com/unitestates/congressional-record/issues'

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["congressionalrecord"]
